server:
  port: 8080

spring:
  application:
    name: todo-microservice

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.todo: DEBUG
    org.springframework: INFO